package Enums;

public enum ORIGIN {
    REGIONS;


    public enum COUNTRIES {
        ARGENTINA,
        AUSTRIA,
        AUSTRALIA,
        CANADA,
        CHILE,
        ESPANA,
        FRANCE,
        DEUTSCHLAND,
        HUNGARY,
        ITALIA,
        NEW_ZEALAND,
        PORTUGAL,
        SOUTH_AFRICA,
        USA;

    }

    public enum AREGENTINA_REGIONS {
        ARGENTINA__MENDOZA_ANDES_MOUNTAINS_FOOTHILLS,
        ARGENTINA__MENDOZA_ANDES_MOUNTAINS_FOOTHILLS__LUJAN_AND_UCO_VALLEY,
        ARGENTINA,

    }

    public enum AUSTRIA_REGIONS {
        AUSTRIA,

    }

    public enum AUSTRALIA_REGIONS {
        AUSTRALIA__SOUTH_EAST,
        AUSTRALIA,

    }

    public enum CANADA_REGIONS {
        CANADA,

    }

    public enum CHILE_REGIONS {
        CHILE__ACONCAGUA,
        CHILE__ACONCAGUA__ACONCAGUA_COSTA,
        CHILE__CENTRAL_VALLEY,
        CHILE__CENTRAL_VALLEY__CASABLANCA_VALLEY,
        CHILE__CENTRAL_VALLEY__COLCHAGUA_VALLEY,
        CHILE__CENTRAL_VALLEY__CURICO_VALLEY,
        CHILE__CENTRAL_VALLEY__MAULE_VALLEY,
        CHILE__CENTRAL_VALLEY__MAULE_VALLEY__LONCOMILLA_VALLEY,
        CHILE,

    }

    public enum SPAIN_REGIONS {
        ARAGON__NORTHERN_SPAIN__CARINENA,
        CALATAYUD,
        CASTILLA_LA_LEON__NORTHERN_SPAIN__RIBERA_DEL_DUERO,
        CASTILLA_LA_MANCHA__CENTRAL_PLAINS__RIOJA_CRIANZA,
        MURCIA__CENTRAL_MEDITERRANEAN_COAST__JUMILLA,
        VALENCIA__CENTRAL_MEDITERRANEAN_COAST,
        VALENCIA__CENTRAL_MEDITERRANEAN_COAST__UTIEL_REQUENA,
        ESPANA,

    }

    public enum FRANCE_REGIONS {
        FRANCE__BORDEAUX__WESTERN_COAST,
        FRANCE__BORDEAUX__WESTERN_COAST__BORDEAUX_SUPERIEUR,
        FRANCE__BORDEAUX__WESTERN_COAST__MONTAGE_SAINT_EMILION,
        FRANCE__BORDEAUX__WESTERN_COAST__POMEROL,
        FRANCE__BORDEAUX__WESTERN_COAST__SAINT_EMILION_GRAND_CRU,
        FRANCE__BORDEAUX__WESTERN_COAST__SAINT_ESTEPHE,
        FRANCE__BORDEAUX__WESTERN_COAST__SAINT_JULIEN,
        FRANCE__BOURGOGNE,
        FRANCE__BOURGOGNE__BEAUJOLAIS,
        FRANCE__BOURGOGNE__BEAUJOLAIS_VILLAGES,
        FRANCE__BOURGOGNE__CHABLIS,
        FRANCE__BOURGOGNE__MACON_VILLAGES,
        FRANCE__COTES_DE_PROVENCE__MEDITERRANEAN_COAST,
        FRANCE__COTES_DU_RHONE__SOUTH_EAST_FRANCE,
        FRANCE__COTES_DU_RHONE__SOUTH_EAST_FRANCE__CHATEAUNEUF_DU_PAPE,
        FRANCE__COTES_DU_RHONE__SOUTH_EAST_FRANCE__COTES_DU_RHONE_VILLAGE,
        FRANCE__COTES_DU_RHONE__SOUTH_EAST_FRANCE__COTES_DU_VENTOUX,
        FRANCE__COTES_DU_RHONE__SOUTH_EAST_FRANCE__TAVEL,
        FRANCE__LANGUEDOC_ROUSILLON__MEDITERRANEAN__LANGUEDOC,
        FRANCE__LANGUEDOC_ROUSILLON__MEDITERRANEAN__PAYS_D_OC,
        FRANCE__LOIRE_VALLEY__CENTRAL__ANJOU,
        FRANCE__LOIRE_VALLEY__WESTERN__MUSCADET_SEVRE_ET_MAINE,
        FRANCE__LOIRE_VALLEY__EASTERN__POUILLY_FUME,
        FRANCE__LOIRE_VALLEY__EASTERN__SANCERRE,
        FRANCE__LOIRE_VALLEY__CENTRAL__TOURAINE,
        FRANCE__LOIRE_VALLEY__CENTRAL__VOUVRAY,
        FRANCE__SOUTH_OF_FRANCE,
        FRANCE__SOUTH_WEST_FRANCE__COTES_DE_GASGOGNE,
        FRANCE__SOUTH_WEST_FRANCE,
        FRANCE__VIN_DE_FRNACE,

    }

    public enum GERMANY_REGIONS {
        DEUTSCHLAND__MOSEL_RIVER__EIFEL_MOUNTAINS__LIEBFRAUMILCH,
        DEUTSCHLAND__NAHE,
        DEUTSCHLAND__PFALZ,
        DEUTSCHLAND__RHEINHESSEN__RHINE_RIVER_LEFT_BANK__AUSLESE,
        DEUTSCHLAND,

    }

    public enum HUNGARY_REGIONS {
        HUNGARY,

    }

    public enum ITALY_REGIONS {
        ITALIA__ABRUZZO__CENTRAL_ADRIATIC_COAST,
        ITALIA__CAMPANIA__SOUTHERN_ITALIA__BENEVENTANO_IGT,
        ITALIA__PIEDMONT__NORTHWESTERN_ITALIA__BARBERA_D_ASTI,
        ITALIA__PIEDMONT__NORTHWESTERN_ITALIA__BAROLO__LANGHE_DISTRICT,
        ITALIA__PUGLIA__HEEL_OF_ITALIA,
        ITALIA__PUGLIA__HEEL_OF_ITALIA__SALICE_SALENTINO,
        ITALIA__SICILIA,
        ITALIA__SICILIA__SANTA_MARGHERITA_DI_BELICE,
        ITALIA__SOUTHERN_ITALIA,
        ITALIA__TRIVENETO_ZONE__NORTHEASTERN__ALTO_ADIGE_AND_TRENITO,
        ITALIA__TRIVENETO_ZONE__NORTHEASTERN__FRIULI_VENEZIA_GIULIA,
        ITALIA__TRIVENETO_ZONE__NORTHEASTERN__VENETO,
        ITALIA__TRIVENETO_ZONE__NORTHEASTERN__VENETO__VALDADIGE,
        ITALIA__TRIVENETO_ZONE__NORTHEASTERN__VENETO__VENEZIA,
        ITALIA__TRIVENETO_ZONE__NORTHEASTERN__VENETO__IGT,
        ITALIA__TRIVENETO_ZONE__NORTHEASTERN__VENETO__VALPOLICELLA,
        ITALIA__TUSCANY_BOLGHERI,
        ITALIA__TUSCANY_BRUNELLO_DI_MONTALCINO,
        ITALIA__TUSCANY_CHIANTI,
        ITALIA__TUSCANY_CHIANTI_RISERVA,
        ITALIA__TUSCANY__TOSCANA,
        ITALIA__TUSCANY__SUPER_TUSCAN,
        ITALIA,

    }

    public enum NEW_ZEALAND_REGIONS {
        NEW_ZEALAND__HAWKES_BAY,
        NEW_ZEALAND__MARLBOROUGH,
        NEW_ZEALAND,

    }

    public enum PORTUGAL_REGIONS {
        DOURO_VALLEY,
        VINHOS_VERDES_REGION__NORTHWEST,
        PORTUGAL,

    }

    public enum SOUTH_AFRICA_REGIONS {
        WESTERN_CAPE,
        WESTERN_CAPE__MCGREGOR_GRAPES,
        SOUTH_AFRICA,

    }

    public enum USA_REGIONS {
        ARIZONA,
        PACIFIC_NORTHWEST__OREGON,
        PACIFIC_NORTHWEST__OREGON__COLUMBIA_GORGE,
        PACIFIC_NORTHWEST__OREGON__SOUTHERN,
        PACIFIC_NORTHWEST__OREGON__WILAMMETTE_VALLEY,
        PACIFIC_NORTHWEST__OREGON__WILAMMETTE__UMPQUA_VALLEY,
        PACIFIC_NORTHWEST__WASHINGTON,
        PACIFIC_NORTHWEST__WASHINGTON__COLUMBIA_RIVER_VALLEY,
        TEXAS,
        TEXAS_CENTRAL,
        TEXAS_NORTHWEST_PLAINS,
        TEXAS_SOUTHWEST,
        CA_CALIFORNIA,
        CA_CENTRAL_COAST,
        CA_CENTRAL_COAST__EDNA_VALLEY,
        CA_CENTRAL_COAST__MONTEREY,
        CA_CENTRAL_COAST__MONTEREY__ARROYO_SECO,
        CA_CENTRAL_COAST__MONTEREY__SAN_LUIS_OBISPO_COUNTY,
        CA_CENTRAL_COAST__MONTEREY__SANTA_LUCIA_HIGHLANDS,
        CA_CENTRAL_COAST__MONTEREY__SANTA_MARIA_VALLEY,
        CA_CENTRAL_COAST__MONTEREY_COUNTY,
        CA_CENTRAL_COAST__SANTA_BARBARA_COUNTY,
        CA_INLAND_VALLEYS__CLARKSBURG,
        CA_INLAND_VALLEYS__LODI,
        CA_NORTH_COAST,
        CA_NORTH_COAST__MENDOCINO_AND_LAKE_COUNTIES,
        CA_NORTH_COAST__MENDOCINO_COUNTY,
        CA_NORTH_COAST__NAPA_VALLEY,
        CA_NORTH_COAST__NAPA_VALLEY__CARNEROS,
        CA_NORTH_COAST__NAPA_VALLEY__OAK_KNOLL_DISTRICT,
        CA_NORTH_COAST__NAPA_VALLEY__STAGS_LEAP_DISTRICT,
        CA_NORTH_COAST__SONOMA_COUNTY,
        CA_NORTH_COAST__SONOMA_COUNTY__SONOMA_VALLEY,
        CA_NORTH_COAST__SONOMA_COUNTY__RUSSIAN_RIVER_VALLEY,
        CA_NORTHERN,
        CA_SOUTHERN,

    }

}
